// Mock database
export interface Product {
  id: number;
  name: string;
  price: number;
  description?: string;
  image?: string;
  rating?: number;
  label?: string;
  category?: string;
  size?: string[];
  color?: string;
  originalPrice?: number;
}

const mockProducts: Product[] = [
  {
    id: 1,
    name: "Yellow Sweater",
    price: 19.99,
    description:
      "Cozy and comfortable yellow sweater, perfect for casual wear and layering",
    image: "/img/product/product-1.jpg",
    rating: 5,
    label: "new",
    category: "women",
    size: ["s", "m", "l", "xl"],
    color: "yellows",
  },
  {
    id: 2,
    name: "Pink Light Jacket",
    price: 29.99,
    description:
      "Stylish lightweight pink jacket, ideal for spring and fall seasons",
    image: "/img/product/product-2.jpg",
    rating: 5,
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "reds",
  },
  {
    id: 3,
    name: "Fall Blouse",
    price: 39.99,
    description:
      "Elegant fall blouse with beautiful colors and comfortable fit",
    image: "/img/product/product-3.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 4,
    name: "Striped Dress shirt",
    price: 9.99,
    description:
      "Classic striped dress shirt, versatile and perfect for professional or casual settings",
    image: "/img/product/product-4.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 5,
    name: "Striped Yellow Shirt",
    price: 14.99,
    description:
      "Vibrant striped yellow shirt with modern style and comfortable fabric",
    image: "/img/product/product-5.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "yellows",
  },
  {
    id: 6,
    name: "Dotted Animal Shirt",
    price: 24.99,
    description:
      "Fun and playful dotted animal print shirt, great for casual everyday wear",
    image: "/img/product/product-6.jpg",
    rating: 5,
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "whites",
  },
  {
    id: 7,
    name: "White Blouse",
    price: 49.99,
    description:
      "Timeless white blouse with elegant design, perfect for both work and social occasions",
    image: "/img/product/product-7.jpg",
    rating: 5,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 8,
    name: "California Sun Shirt",
    price: 34.99,
    description:
      "Bright and sunny California-inspired shirt, perfect for beach trips and warm weather",
    image: "/img/product/product-8.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "yellows",
  },
  {
    id: 9,
    name: "Furry hooded parka",
    price: 59,
    image: "/img/shop/shop-1.jpg",
    rating: 5,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "black",
  },
  {
    id: 10,
    name: "Flowy striped skirt",
    price: 49,
    image: "/img/shop/shop-2.jpg",
    rating: 5,
    category: "women",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 11,
    name: "Croc-effect bag",
    price: 59,
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 12,
    name: "Dark wash Xavi jeans",
    price: 59,
    image: "/img/shop/shop-4.jpg",
    rating: 5,
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 13,
    name: "Ankle-cuff sandals",
    price: 49,
    originalPrice: 59,
    image: "/img/shop/shop-5.jpg",
    rating: 5,
    label: "sale",
    category: "accessories",
    size: ["xs", "s", "m", "l"],
    color: "beige",
  },
  {
    id: 14,
    name: "Contrasting sunglasses",
    price: 59,
    image: "/img/shop/shop-6.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 15,
    name: "Circular pendant earrings",
    price: 59,
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "reds",
  },
  {
    id: 16,
    name: "Cotton T-Shirt",
    price: 59,
    image: "/img/shop/shop-8.jpg",
    rating: 5,
    label: "out-of-stock",
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 17,
    name: "Water resistant zips backpack",
    price: 49,
    originalPrice: 59,
    image: "/img/shop/shop-9.jpg",
    rating: 5,
    label: "sale",
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 18,
    name: "Slim Fit Chinos",
    price: 45.99,
    description:
      "Modern slim fit chinos with stretch fabric for comfort and style",
    image: "/img/product/product-1.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 19,
    name: "Leather Crossbody Bag",
    price: 79.99,
    description: "Premium leather crossbody bag with adjustable strap",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    label: "new",
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 20,
    name: "Floral Print Maxi Dress",
    price: 64.99,
    originalPrice: 89.99,
    description: "Elegant floral print maxi dress perfect for summer occasions",
    image: "/img/product/product-2.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "reds",
  },
  {
    id: 21,
    name: "Athletic Running Shoes",
    price: 89.99,
    description: "High-performance running shoes with cushioned sole",
    image: "/img/shop/shop-5.jpg",
    rating: 4,
    category: "accessories",
    size: ["s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 22,
    name: "Denim Jacket",
    price: 69.99,
    description: "Classic denim jacket with vintage wash finish",
    image: "/img/product/product-4.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 23,
    name: "Knit Cardigan",
    price: 54.99,
    description: "Soft knit cardigan with button front closure",
    image: "/img/product/product-1.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "beige",
  },
  {
    id: 24,
    name: "Plaid Flannel Shirt",
    price: 39.99,
    description: "Comfortable plaid flannel shirt for casual wear",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "reds",
  },
  {
    id: 25,
    name: "Wide Brim Sun Hat",
    price: 29.99,
    description: "Stylish wide brim hat with UV protection",
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "beige",
  },
  {
    id: 26,
    name: "High Waist Yoga Pants",
    price: 44.99,
    description: "Stretchy high waist yoga pants with moisture-wicking fabric",
    image: "/img/product/product-3.jpg",
    rating: 5,
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 27,
    name: "Polo Shirt",
    price: 34.99,
    description: "Classic polo shirt in breathable cotton blend",
    image: "/img/product/product-4.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 28,
    name: "Wrap Around Scarf",
    price: 24.99,
    description: "Soft cashmere blend scarf in versatile neutral tones",
    image: "/img/shop/shop-2.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "beige",
  },
  {
    id: 29,
    name: "Slim Fit Blazer",
    price: 119.99,
    originalPrice: 159.99,
    description: "Tailored slim fit blazer for professional occasions",
    image: "/img/product/product-7.jpg",
    rating: 5,
    label: "sale",
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 30,
    name: "Ripped Boyfriend Jeans",
    price: 59.99,
    description: "Trendy ripped boyfriend jeans with relaxed fit",
    image: "/img/shop/shop-4.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 31,
    name: "Leather Belt",
    price: 34.99,
    description: "Genuine leather belt with classic buckle",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 32,
    name: "Hoodie Sweatshirt",
    price: 49.99,
    description: "Comfortable hoodie with kangaroo pocket",
    image: "/img/product/product-1.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "yellows",
  },
  {
    id: 33,
    name: "Midi Pencil Skirt",
    price: 44.99,
    description: "Professional midi pencil skirt with side slit",
    image: "/img/product/product-3.jpg",
    rating: 5,
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "blacks",
  },
  {
    id: 34,
    name: "Aviator Sunglasses",
    price: 69.99,
    originalPrice: 89.99,
    description: "Classic aviator sunglasses with polarized lenses",
    image: "/img/shop/shop-6.jpg",
    rating: 5,
    label: "sale",
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 35,
    name: "Graphic Tee",
    price: 24.99,
    description: "Cotton graphic tee with modern print design",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 36,
    name: "Silk Blouse",
    price: 74.99,
    description: "Luxurious silk blouse with elegant drape",
    image: "/img/product/product-7.jpg",
    rating: 5,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "reds",
  },
  {
    id: 37,
    name: "Canvas Sneakers",
    price: 54.99,
    description: "Classic canvas sneakers in timeless style",
    image: "/img/shop/shop-5.jpg",
    rating: 4,
    category: "accessories",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 38,
    name: "Cargo Pants",
    price: 64.99,
    description: "Utility cargo pants with multiple pockets",
    image: "/img/product/product-4.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 39,
    name: "Clutch Evening Bag",
    price: 49.99,
    description: "Elegant clutch bag perfect for evening events",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 40,
    name: "Linen Summer Dress",
    price: 59.99,
    originalPrice: 79.99,
    description: "Breathable linen dress for warm weather",
    image: "/img/product/product-2.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 41,
    name: "Bomber Jacket",
    price: 89.99,
    description: "Stylish bomber jacket with ribbed cuffs",
    image: "/img/product/product-4.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 42,
    name: "Stud Earrings",
    price: 39.99,
    description: "Elegant stud earrings in sterling silver",
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    label: "new",
    category: "accessories",
    size: ["onesize"],
    color: "whites",
  },
  {
    id: 43,
    name: "Turtleneck Sweater",
    price: 54.99,
    description: "Warm turtleneck sweater in soft merino wool",
    image: "/img/product/product-1.jpg",
    rating: 4,
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "blacks",
  },
  {
    id: 44,
    name: "Swim Trunks",
    price: 34.99,
    description: "Quick-dry swim trunks with mesh lining",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 45,
    name: "Tote Bag",
    price: 44.99,
    description: "Spacious canvas tote bag for everyday use",
    image: "/img/shop/shop-3.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "beige",
  },
  {
    id: 46,
    name: "Pleated Midi Skirt",
    price: 49.99,
    originalPrice: 69.99,
    description: "Elegant pleated midi skirt with elastic waist",
    image: "/img/product/product-3.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "reds",
  },
  {
    id: 47,
    name: "Henley Shirt",
    price: 39.99,
    description: "Casual henley shirt with button placket",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 48,
    name: "Statement Necklace",
    price: 54.99,
    description: "Bold statement necklace to elevate any outfit",
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "yellows",
  },
  {
    id: 49,
    name: "Quilted Vest",
    price: 69.99,
    description: "Lightweight quilted vest with zip front",
    image: "/img/product/product-1.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 50,
    name: "Track Pants",
    price: 44.99,
    description: "Athletic track pants with side stripes",
    image: "/img/product/product-4.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 51,
    name: "Bucket Hat",
    price: 24.99,
    description: "Trendy bucket hat in cotton twill",
    image: "/img/shop/shop-7.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 52,
    name: "Wrap Dress",
    price: 69.99,
    originalPrice: 94.99,
    description: "Flattering wrap dress with tie waist",
    image: "/img/product/product-2.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "reds",
  },
  {
    id: 53,
    name: "Long Sleeve Tee",
    price: 29.99,
    description: "Basic long sleeve tee in soft cotton",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 54,
    name: "Shoulder Bag",
    price: 64.99,
    description: "Versatile shoulder bag with adjustable strap",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 55,
    name: "Palazzo Pants",
    price: 54.99,
    description: "Flowy palazzo pants with wide legs",
    image: "/img/product/product-3.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 56,
    name: "Quarter Zip Pullover",
    price: 59.99,
    description: "Athletic quarter zip pullover in performance fabric",
    image: "/img/product/product-1.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 57,
    name: "Bracelet Set",
    price: 34.99,
    description: "Layered bracelet set with mixed metals",
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "yellows",
  },
  {
    id: 58,
    name: "Bodycon Dress",
    price: 49.99,
    originalPrice: 64.99,
    description: "Figure-hugging bodycon dress for night out",
    image: "/img/product/product-2.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "blacks",
  },
  {
    id: 59,
    name: "Windbreaker",
    price: 74.99,
    description: "Lightweight windbreaker with hood",
    image: "/img/product/product-4.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "yellows",
  },
  {
    id: 60,
    name: "Ankle Boots",
    price: 89.99,
    description: "Leather ankle boots with low heel",
    image: "/img/shop/shop-5.jpg",
    rating: 5,
    category: "accessories",
    size: ["s", "m", "l"],
    color: "blacks",
  },
  {
    id: 61,
    name: "Tank Top",
    price: 19.99,
    description: "Ribbed tank top in stretchy fabric",
    image: "/img/product/product-7.jpg",
    rating: 4,
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "whites",
  },
  {
    id: 62,
    name: "Sweatpants",
    price: 44.99,
    description: "Comfortable sweatpants with drawstring waist",
    image: "/img/product/product-4.jpg",
    rating: 4,
    label: "new",
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 63,
    name: "Woven Belt",
    price: 29.99,
    description: "Stylish woven belt with metal buckle",
    image: "/img/shop/shop-3.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "beige",
  },
  {
    id: 64,
    name: "Off-Shoulder Top",
    price: 39.99,
    originalPrice: 54.99,
    description: "Trendy off-shoulder top with elastic neckline",
    image: "/img/product/product-7.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "reds",
  },
  {
    id: 65,
    name: "Dress Shirt",
    price: 54.99,
    description: "Classic dress shirt in non-iron fabric",
    image: "/img/product/product-4.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 66,
    name: "Watch",
    price: 129.99,
    description: "Minimalist watch with leather strap",
    image: "/img/shop/shop-6.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 67,
    name: "Cropped Cardigan",
    price: 44.99,
    description: "Cropped cardigan with pearl buttons",
    image: "/img/product/product-1.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "beige",
  },
  {
    id: 68,
    name: "Chino Shorts",
    price: 39.99,
    description: "Casual chino shorts with flat front",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 69,
    name: "Satchel Bag",
    price: 74.99,
    description: "Structured satchel bag with top handle",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 70,
    name: "Tie-Dye Dress",
    price: 54.99,
    originalPrice: 74.99,
    description: "Vibrant tie-dye maxi dress for bohemian style",
    image: "/img/product/product-2.jpg",
    rating: 4,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "yellows",
  },
  {
    id: 71,
    name: "Rugby Shirt",
    price: 49.99,
    description: "Striped rugby shirt with collar",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "reds",
  },
  {
    id: 72,
    name: "Hair Accessories Set",
    price: 24.99,
    description: "Trendy hair clips and scrunchies set",
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "beige",
  },
  {
    id: 73,
    name: "Peplum Top",
    price: 44.99,
    description: "Flattering peplum top with fitted bodice",
    image: "/img/product/product-7.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "whites",
  },
  {
    id: 74,
    name: "Peacoat",
    price: 129.99,
    description: "Classic wool blend peacoat for winter",
    image: "/img/product/product-4.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 75,
    name: "Leather Gloves",
    price: 44.99,
    description: "Soft leather gloves with fleece lining",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["s", "m", "l"],
    color: "blacks",
  },
  {
    id: 76,
    name: "Halter Neck Dress",
    price: 69.99,
    originalPrice: 89.99,
    description: "Elegant halter neck dress for special occasions",
    image: "/img/product/product-2.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "reds",
  },
  {
    id: 77,
    name: "Button-Down Shirt",
    price: 44.99,
    description: "Versatile button-down in oxford cloth",
    image: "/img/product/product-5.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 78,
    name: "Coin Purse",
    price: 19.99,
    description: "Compact coin purse with zip closure",
    image: "/img/shop/shop-3.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "reds",
  },
  {
    id: 79,
    name: "Jumpsuit",
    price: 79.99,
    description: "Sleeveless jumpsuit with wide legs",
    image: "/img/product/product-3.jpg",
    rating: 5,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "blacks",
  },
  {
    id: 80,
    name: "Thermal Shirt",
    price: 34.99,
    description: "Warm thermal base layer shirt",
    image: "/img/product/product-1.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 81,
    name: "Beanie",
    price: 19.99,
    description: "Cozy knit beanie for cold weather",
    image: "/img/shop/shop-7.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 82,
    name: "Romper",
    price: 49.99,
    originalPrice: 64.99,
    description: "Playful romper with adjustable straps",
    image: "/img/product/product-2.jpg",
    rating: 4,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "beige",
  },
  {
    id: 83,
    name: "V-Neck Sweater",
    price: 54.99,
    description: "Classic v-neck sweater in lambswool",
    image: "/img/product/product-1.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 84,
    name: "Ring Set",
    price: 39.99,
    description: "Stackable ring set in mixed finishes",
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "yellows",
  },
  {
    id: 85,
    name: "Tunic Top",
    price: 44.99,
    description: "Loose-fit tunic with side slits",
    image: "/img/product/product-7.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 86,
    name: "Joggers",
    price: 49.99,
    description: "Tapered joggers with elastic cuffs",
    image: "/img/product/product-4.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 87,
    name: "Crossbody Phone Bag",
    price: 29.99,
    description: "Compact crossbody bag for phone and essentials",
    image: "/img/shop/shop-3.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "reds",
  },
  {
    id: 88,
    name: "Skater Skirt",
    price: 39.99,
    originalPrice: 49.99,
    description: "Flared skater skirt with high waist",
    image: "/img/product/product-3.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "blacks",
  },
  {
    id: 89,
    name: "Crew Neck Sweater",
    price: 49.99,
    description: "Comfortable crew neck sweater in cotton blend",
    image: "/img/product/product-1.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "yellows",
  },
  {
    id: 90,
    name: "Baseball Cap",
    price: 24.99,
    description: "Classic baseball cap with adjustable strap",
    image: "/img/shop/shop-7.jpg",
    rating: 4,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 91,
    name: "Cami Dress",
    price: 44.99,
    description: "Slip-style cami dress in satin finish",
    image: "/img/product/product-2.jpg",
    rating: 5,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "reds",
  },
  {
    id: 92,
    name: "Work Pants",
    price: 59.99,
    description: "Professional work pants with creased front",
    image: "/img/product/product-4.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blacks",
  },
  {
    id: 93,
    name: "Laptop Bag",
    price: 69.99,
    description: "Padded laptop bag with multiple compartments",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 94,
    name: "Slip Dress",
    price: 59.99,
    originalPrice: 79.99,
    description: "Silky slip dress with adjustable straps",
    image: "/img/product/product-2.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "beige",
  },
  {
    id: 95,
    name: "Mock Neck Sweater",
    price: 54.99,
    description: "Modern mock neck sweater in fine gauge knit",
    image: "/img/product/product-1.jpg",
    rating: 4,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "blues",
  },
  {
    id: 96,
    name: "Chain Necklace",
    price: 44.99,
    description: "Chunky chain necklace in gold tone",
    image: "/img/shop/shop-7.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "yellows",
  },
  {
    id: 97,
    name: "Smock Dress",
    price: 54.99,
    description: "Comfortable smock dress with pockets",
    image: "/img/product/product-2.jpg",
    rating: 4,
    label: "new",
    category: "women",
    size: ["xs", "s", "m", "l", "xl"],
    color: "whites",
  },
  {
    id: 98,
    name: "Utility Jacket",
    price: 79.99,
    description: "Multi-pocket utility jacket in durable canvas",
    image: "/img/product/product-4.jpg",
    rating: 5,
    category: "men",
    size: ["s", "m", "l", "xl"],
    color: "beige",
  },
  {
    id: 99,
    name: "Wallet",
    price: 34.99,
    description: "Slim bifold wallet in genuine leather",
    image: "/img/shop/shop-3.jpg",
    rating: 5,
    category: "accessories",
    size: ["onesize"],
    color: "blacks",
  },
  {
    id: 100,
    name: "Shift Dress",
    price: 64.99,
    originalPrice: 84.99,
    description: "Classic shift dress with clean lines",
    image: "/img/product/product-7.jpg",
    rating: 5,
    label: "sale",
    category: "women",
    size: ["xs", "s", "m", "l"],
    color: "blues",
  },
];

export interface PaginationParams {
  page?: number;
  limit?: number;
  categories?: string[];
  sizes?: string[];
  colors?: string[];
}

export interface PaginatedProducts {
  products: Product[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export async function getProducts(
  params?: PaginationParams
): Promise<PaginatedProducts> {
  // Simulate database delay
  await new Promise((resolve) => setTimeout(resolve, 100));

  const page = params?.page || 1;
  const limit = params?.limit || 12;
  const categories = params?.categories || [];
  const sizes = params?.sizes || [];
  const colors = params?.colors || [];
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;

  const filteredProducts = mockProducts
    .filter((product) => {
      if (product.category === undefined) return false;
      if (categories.length === 0) {
        return true;
      }
      return categories.includes(product.category);
    })
    .filter((product) => {
      if (product.size === undefined) return false;
      if (sizes.length === 0) return true;
      return sizes.some((size) => product.size!.includes(size));
    })
    .filter((product) => {
      if (product.color === undefined) return false;
      if (colors.length === 0) return true;
      return colors.includes(product.color);
    });

  const paginatedProducts = filteredProducts.slice(startIndex, endIndex);

  const total = filteredProducts.length;
  const totalPages = Math.ceil(total / limit);

  return {
    products: paginatedProducts,
    total,
    page,
    limit,
    totalPages,
  };
}

export async function getProductById(id: number): Promise<Product | null> {
  await new Promise((resolve) => setTimeout(resolve, 100));
  return mockProducts.find((p) => p.id === id) || null;
}
